// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';

void f(p) async { await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
); 
}


/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByMVtyV53L_qDMQpiVpo3SuUdXgr7xEFI',
    appId: '1:117422290157:web:c93f45aac89aa8b9c2c8e4',
    messagingSenderId: '117422290157',
    projectId: 'todolist-db-e9fe9',
    authDomain: 'todolist-db-e9fe9.firebaseapp.com',
    storageBucket: 'todolist-db-e9fe9.firebasestorage.app',
    measurementId: 'G-H9JS4TN9MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGIXvFXTD5VxUcT8JgbBJpy4ISopHSSdc',
    appId: '1:117422290157:android:612bba448109f3a8c2c8e4',
    messagingSenderId: '117422290157',
    projectId: 'todolist-db-e9fe9',
    storageBucket: 'todolist-db-e9fe9.firebasestorage.app',
  );
}
